name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Build docker image
      run: make build
      
    - name: Test docker image
      run: make test
      
    - name: Publish docker image
      run: echo "Skipping publishing to dockerHub"
      
    - name: Cleanup workspace
      if: always()
      run: make clean
